name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - dev-deploy

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /home/ec2-user/app
          # SCRIPT_BEFORE: |
          #   whoami
          #   ls -al
          SCRIPT_AFTER: |
            cd /home/ec2-user/app
            yarn install
            echo "yarn install completed"
            kill -9 $(pgrep node)
            echo "cleaned up previous processes"
            export MONGO_URI=$(cat /app/mongo_uri); export PORT=3000; nohup node index.js > /dev/null 2>&1 &
            echo "newest commit is running"